language: node_js
node_js:
  - 7.7.1
notifications:
  email: false
  slack:
    secure: lVBTN1WNCLqMZhF6mfZZjhZWA+xZuP04+0R7rMPnRmZHLSYef/aRkyVvgZancEh3yQ1ZSavHFkJYa1St1+wkTRTbTzf8ZnVNA3+ph0L1nN2I7jKLvl+rjRXgY+oalN0TQG1CAss918EV20dfjT17LdVa70D95OJqDDNZUHJt3MPaAag9L1e2Ei2f0s8OW9l5/IrryI5ata/00JlJbXTTpn2U4Q5l0E7eiIeN57L/0qZFcqW1Io48Hqf069t+150Xskblyb0eLmW2IyqZwWCp8XroEH7KXrr5oV9IEGI12f3rh6mLudHevkj5rzEpDgclR1sSUU22Z49xyEQgPrddzRabeXEYFCHhPIbYqOUf0Xg7CqGR8WOMEdflzseOipobdOJS/bI4qQBHRucVc5r65yq+ARPPooHP1Hgsinafvk7AxVprW9lo7kCvEGDqUBnD8IrJyxiU+t+gvElW/t1Kk4tL0DcQHPdvkSQuGwH0d4aQ1uZ3kYDq4Km48HivdsaQaU3lF0c7chnz3HGWrU1Mpaf30kPXcHtHRXd4BJM7vEExEtvvjIxB9JUW9StaMnPmP5aMfjex7n6EqySOrx7BF5P/9cAJbghdp5l1qC3NioB4siK5z++c3cesH6i7WRXMGxSrbz5F/eF4KYMYv2bhDYgw90a+jnmKxu+R7XG7/68=
